services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  adminer:
    image: adminer:4
    container_name: adminer_container
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - postgres
      - mysql
    networks:
      - my_network

volumes:
  postgres_data:
  mysql_data:

networks:
  my_network:
    driver: bridge
